version: 2.0

jobs: 
  "build-1": 
    docker: 
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: mydockerhub-user
        image: "cimg/php:7.3"
    steps: 
      - checkout
      - run: "sudo composer install -n --prefer-dist"
      - run: "sudo composer self-update"
      - run: "sudo composer update --no-progress --prefer-dist --profile"
      - run: 
          command: "composer test"
          name: Test PHP7.3

  "build-2": 
    docker: 
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: mydockerhub-user
        image: "cimg/php:7.4"
    steps: 
      - checkout
      - run: "sudo composer install -n --prefer-dist"
      - run: "sudo composer self-update"
      - run: "sudo composer update --no-progress --prefer-dist --profile"
      - run: 
          command: "composer test"
          name: Test PHP7.4

  "build-3": 
    docker: 
      - auth: 
          password: $DOCKERHUB_PASSWORD
          username: mydockerhub-user
        image: "cimg/php:8.0"
    steps: 
      - checkout
      - run: "sudo composer install -n --prefer-dist"
      - run: "sudo composer self-update"
      - run: "sudo composer update --no-progress --prefer-dist --profile"
      - run: 
          command: "composer test"
          name: Test PHP8

workflows:
  version: 2
  build:
      jobs:
        - "build-1"
        - "build-2"
        - "build-3"